# Generated by Django 4.0.5 on 2022-08-30 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marc', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='docfile1',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='docfile2',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='attached',
            field=models.FileField(upload_to='ducments/%Y/%m/%d', verbose_name='첨부 파일'),
        ),
    ]
