# Generated by Django 4.1.2 on 2022-10-31 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marc', '0006_question_docfile1_question_docfile2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduInsName', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='attached',
        ),
        migrations.RemoveField(
            model_name='document',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='modify_date',
        ),
        migrations.AddField(
            model_name='document',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='uploadedFile',
            field=models.FileField(default=django.utils.timezone.now, upload_to='result/', verbose_name='첨부파일'),
            preserve_default=False,
        ),
    ]
