# Generated by Django 4.1.2 on 2022-11-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marc', '0007_eduinstitution_remove_document_attached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='doctype1',
            field=models.TextField(default='application/pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='doctype2',
            field=models.TextField(default='application/pdf'),
            preserve_default=False,
        ),
    ]
