# Generated by Django 4.1.2 on 2022-12-02 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marc', '0008_question_doctype1_question_doctype2'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='certificate_item',
            field=models.TextField(default='집합교육'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='department',
            field=models.TextField(default='경영지원부'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='education_cost',
            field=models.TextField(default='무료'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='education_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='education_institute',
            field=models.TextField(default='지방공기업평가원'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='education_part',
            field=models.TextField(default='기타'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='education_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='education_time',
            field=models.TextField(default='2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='education_type',
            field=models.TextField(default='집합교육'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='memo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.TextField(default='김상현'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='relate_Competency',
            field=models.TextField(default='기타역량'),
            preserve_default=False,
        ),
    ]
