# Generated by Django 4.1.2 on 2022-12-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marc', '0009_question_certificate_item_question_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='job_grade',
            field=models.TextField(default='9급'),
            preserve_default=False,
        ),
    ]
